### ISSUE TITLE
Versioning issue?

### ISSUE THREAD

**Issue by ryanbateman** [twitterdev/twitter-for-bigquery#11]
Hi,

Apologies - I prefer not to use Github issues for help requests but I can't find a relevant forum or community.  I'm attempting to set this up and don't appear to be able to run `setup.py`.  The error it responds with is: 

```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    container_template = Template(container_template).render(config)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 964, in render
    vars = dict(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/config.py", line 474, in __getitem__
    return self.evaluate(rv)
  File "/usr/local/lib/python2.7/site-packages/config.py", line 407, in evaluate
    item = item.evaluate(self)
  File "/usr/local/lib/python2.7/site-packages/config.py", line 1025, in evaluate
    rv = lhs - rhs
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

This seems like it'd be a package version issue of some kind but Im relatively inexperienced with python and would appreciate any assistance.  Thanks.

**Comment by ryanbateman** [comment]
Issue was in fact an error in the configuration file. Closed.
